import test from 'node:test'
import assert from 'node:assert/strict'
import {PM_TEMPLATES} from '../src/lib/pmTemplates.js'
import {emptyPMResults,nextPMDate,validatePMExecution,validatePMStandard,isPMOverdue} from '../src/lib/pm.js'
import {pmMetrics,tpmMetrics} from '../src/lib/kpi.js'
const standard=()=>({...structuredClone(PM_TEMPLATES[0]),status:'approved',std_minutes:30,reference:'คู่มือรุ่นทดสอบ หน้า 20',machine_scope:'เครื่องทดสอบ',prepared_by_name:'ผู้จัดทำ',reviewer_name:'ผู้ทวนสอบ'})
const work=items=>({results:items.map(i=>({item_id:i.id,result:'normal',note:'',measured_value:''})),stop_minutes:0,performed_by_name:'ช่างทดสอบ',result_summary:'ทำ PM ตามรายการ',verification_note:'ทดสอบคืนเครื่องผ่าน',safety_confirmed:true})
test('PM templates have five independent cycles, methods and acceptance criteria',()=>{assert.equal(PM_TEMPLATES.length,5);for(const s of PM_TEMPLATES){assert.equal(s.status,'template');assert.ok(s.items.every(i=>i.method&&i.criterion));assert.equal(emptyPMResults(s.items).filter(r=>r.result).length,0)}})
test('PM approval requires model, manufacturer reference and named review',()=>{assert.throws(()=>validatePMStandard({...standard(),reference:''}),/เอกสารอ้างอิง/);assert.equal(validatePMStandard(standard()).items.length,6)})
test('PM cannot finish unfinished or all-NA checks',()=>{const s=standard(),f=work(s.items);f.results[0].result='';assert.throws(()=>validatePMExecution(s.items,f),/ยังไม่ได้บันทึก/);f.results=f.results.map(r=>({...r,result:'na',note:'ไม่มีระบบนี้'}));assert.throws(()=>validatePMExecution(s.items,f),/ไม่เกี่ยวข้องทุกข้อ/);assert.doesNotThrow(()=>validatePMExecution(s.items,{...f,results:[]} ,false))})
test('PM abnormal and corrected work requires an explanation and real handover',()=>{const s=standard(),f=work(s.items);f.results[0].result='abnormal';assert.throws(()=>validatePMExecution(s.items,f),/ระบุปัญหา/);f.results[0].note='พบสายรั่ว รอเปลี่ยน';f.safety_confirmed=false;assert.throws(()=>validatePMExecution(s.items,f),/คืนสภาพ/);f.safety_confirmed=true;assert.equal(validatePMExecution(s.items,f).stop_minutes,0)})
test('PM measured zero is valid; an out-of-range pass is rejected',()=>{const items=[{id:'pressure',name:'ค่าทดสอบ',type:'measurement',min_value:0,max_value:5,unit:'bar'}],f=work(items);f.results[0].measured_value=0;assert.equal(validatePMExecution(items,f).results[0].measured_value,0);f.results[0].measured_value=7;assert.throws(()=>validatePMExecution(items,f),/นอกเกณฑ์/);f.results[0].result='abnormal';f.results[0].note='ค่าเกินเกณฑ์ ส่งตรวจ';assert.doesNotThrow(()=>validatePMExecution(items,f))})
test('PM next cycle clamps month-end and leap years',()=>{assert.equal(nextPMDate('2026-01-31','monthly'),'2026-02-28');assert.equal(nextPMDate('2024-02-29','annual'),'2025-02-28');assert.equal(nextPMDate('2026-12-29','weekly'),'2027-01-05')})
test('PM on-time compliance excludes late completions; TPM metric excludes PM',()=>{const schedule=[{due_date:'2026-01-05',status:'completed',completed_at:'2026-01-05T08:00:00'},{due_date:'2026-01-06',status:'completed',completed_at:'2026-01-08T08:00:00'}];const m=pmMetrics(schedule,'2026-01-01','2026-01-31');assert.equal(m.completed,2);assert.equal(m.onTime,1);assert.equal(m.compliance,50);assert.equal(tpmMetrics([{planned_date:'2026-01-01',job_status:'completed',work_type:'pm_scheduled'}],'2026-01-01','2026-01-31').rows.length,0);assert.equal(isPMOverdue({due_date:'2026-01-05',status:'planned'},'2026-01-05'),false)})
