import React,{useEffect,useMemo,useState} from 'react'
import {Search,PackageOpen,Wrench,CalendarClock,UserRound} from '../icons.jsx'
import {Button,Badge,Empty,PageIntro,SelectMenu} from '../components/UI.jsx'
import FollowUpModal from '../components/FollowUpModal.jsx'
import {decodeActionResult} from '../lib/actionResult.js'
import {FOLLOWUP_STATUS,followUpNext,isFollowUpOverdue} from '../lib/followUpView.js'
import {fmtDate,isoDate,rolePlanner} from '../lib/utils.js'
export default function FollowUp({profile,findings,technicians,onSaveAction,onCreateTPM,initialFinding,onConsumedInitial}){
 const [status,setStatus]=useState('active'),[priority,setPriority]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(null)
 const today=isoDate()
 useEffect(()=>{if(!initialFinding)return;const found=findings.find(f=>f.id===initialFinding);if(found)setSelected(found);onConsumedInitial?.()},[initialFinding,findings])
 const ownerName=f=>(technicians||[]).find(t=>t.id===f.owner_profile_id)?.full_name||'ยังไม่มอบหมาย'
 const rows=useMemo(()=>findings.filter(f=>status==='all'||(status==='active'?f.status!=='closed':status==='overdue'?isFollowUpOverdue(f,today):f.status===status)).filter(f=>!priority||f.priority===priority).filter(f=>!q||`${f.machines?.machine_no||''} ${f.finding} ${ownerName(f)} ${f.permanent_action||''}`.toLowerCase().includes(q.trim().toLowerCase())).sort((a,b)=>Number(isFollowUpOverdue(b,today))-Number(isFollowUpOverdue(a,today))||({A:0,B:1,C:2}[a.priority]??9)-({A:0,B:1,C:2}[b.priority]??9)||(a.target_date||'9999').localeCompare(b.target_date||'9999')),[findings,status,priority,q,technicians,today])
 const stats=[{id:'active',label:'งานค้าง',count:findings.filter(f=>f.status!=='closed').length},{id:'overdue',label:'เกินกำหนด',count:findings.filter(f=>isFollowUpOverdue(f,today)).length},{id:'verification',label:'รอตรวจยืนยัน',count:findings.filter(f=>f.status==='verification').length},{id:'closed',label:'ปิดงานแล้ว',count:findings.filter(f=>f.status==='closed').length}]
 return <><PageIntro title="Follow-up" th="ติดตามการแก้ไข" description="เลือกปัญหา → วางแผนแก้ไข → บันทึกผลจริง → ตรวจยืนยันและปิดงาน"/>
 <section className="followup-overview" aria-label="สรุปงานติดตาม">{stats.map(s=><button key={s.id} className={`followup-count ${status===s.id?'active':''} ${s.id==='overdue'&&s.count?'urgent':''}`} aria-pressed={status===s.id} onClick={()=>setStatus(s.id)}><span>{s.label}</span><strong>{s.count}</strong><small>กดดูรายการ</small></button>)}</section>
 <section className="followup-filters"><div className="search-box"><Search size={18}/><input aria-label="ค้นหางานติดตาม" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาเครื่อง ปัญหา หรือผู้รับผิดชอบ"/></div><label>สถานะ<SelectMenu value={status} onChange={setStatus} options={[{value:'active',label:'งานที่ยังไม่ปิด'},{value:'all',label:'ทุกงาน'},{value:'overdue',label:'เกินกำหนด'},...Object.entries(FOLLOWUP_STATUS).map(([value,label])=>({value,label}))]}/></label><label>ความสำคัญ<SelectMenu value={priority} onChange={setPriority} options={[{value:'',label:'ทุกระดับ'},{value:'A',label:'A · เร่งด่วน'},{value:'B',label:'B · สำคัญ'},{value:'C',label:'C · ทั่วไป'}]}/></label></section>
 <div className="followup-list-heading"><span>แสดง {rows.length} งาน</span>{(q||priority||status!=='active')&&<Button size="sm" variant="ghost" onClick={()=>{setQ('');setPriority('');setStatus('active')}}>ล้างตัวกรอง</Button>}</div>
 <div className="follow-grid action-tracker-grid">{rows.length?rows.map(f=>{const evidence=decodeActionResult(f.verification_note||''),closed=f.status==='closed',overdue=isFollowUpOverdue(f,today),photos=f.attachments||[];return <article className={`follow-card-pro follow-action-card followup-compact ${closed?'is-closed':''} ${overdue?'is-overdue':''}`} key={f.id}>
 <header><span className="machine-code">{f.machines?.machine_no||'ไม่ระบุเครื่อง'}</span><div className="defect-badges"><Badge tone={f.priority==='A'?'red':f.priority==='B'?'amber':'neutral'}>{f.priority||'—'}</Badge><Badge tone={closed?'green':f.status==='verification'?'purple':String(f.status).startsWith('waiting')?'amber':'blue'}>{FOLLOWUP_STATUS[f.status]||f.status}</Badge></div></header>
 <div className="followup-problem"><h3>{f.finding}</h3>{f.risk&&<p>{f.risk}</p>}</div>
 <div className="followup-owner-date"><div><UserRound size={16}/><span>ผู้รับผิดชอบ<b>{ownerName(f)}</b></span></div><div className={overdue?'overdue-date':''}><CalendarClock size={16}/><span>{closed?'วันที่กำหนดเดิม':'กำหนดเสร็จ'}<b>{f.target_date?fmtDate(f.target_date):'ยังไม่กำหนด'}{overdue&&<em>เกินกำหนด</em>}</b></span></div></div>
 <div className="followup-next"><span>{closed?'ผลการติดตาม':'ทำอะไรต่อ'}</span><b>{followUpNext(f)}</b></div>
 {(f.spare_required||f.need_machine_stop)&&<div className="followup-requirements">{f.spare_required&&<span><PackageOpen size={15}/>ต้องใช้อะไหล่</span>}{f.need_machine_stop&&<span><Wrench size={15}/>ต้องหยุดเครื่อง</span>}</div>}
 <details className="followup-details"><summary>รายละเอียดแผนและผล{photos.length>0?` · ${photos.length} รูป`:''}</summary><dl>{f.finding?.length>120&&<><dt>ปัญหาที่พบ (ข้อความเต็ม)</dt><dd>{f.finding}</dd></>}{f.permanent_action&&<><dt>แผนแก้ไข</dt><dd>{f.permanent_action}</dd></>}{f.temporary_action&&<><dt>ควบคุมปัญหาชั่วคราว</dt><dd>{f.temporary_action}</dd></>}{evidence.work_result&&<><dt>สิ่งที่ทำจริง</dt><dd>{evidence.work_result}</dd></>}{evidence.verification_note&&<><dt>ผลตรวจยืนยัน</dt><dd>{evidence.verification_note}</dd></>}{!f.permanent_action&&!evidence.work_result&&<dd>ยังไม่มีแผนหรือผลดำเนินการ</dd>}</dl>{photos.length>0&&<div className="follow-photo-strip">{photos.map(p=><a key={p.id} href={p.signed_url||'#'} target="_blank" rel="noreferrer"><img src={p.signed_url} alt={p.file_name||'รูปจุดผิดปกติ'}/></a>)}</div>}</details>
 {rolePlanner(profile.role)&&<footer><Button icon={Wrench} variant={closed?'soft':'primary'} onClick={()=>setSelected(f)}>{closed?'ดูรายละเอียด':f.status==='open'?'วางแผนแก้ไข':f.status==='verification'?'ตรวจยืนยัน / ปิดงาน':'บันทึกความคืบหน้า'}</Button>{!closed&&<Button variant="ghost" onClick={()=>onCreateTPM(f)}>นำเข้าแผน TPM</Button>}</footer>}
 </article>}):<Empty title="ไม่มีงานตามตัวกรองนี้" text="ลองค้นหาใหม่ หรือเลือกทุกงานเพื่อดูประวัติที่ปิดแล้ว"/>}</div>
 <FollowUpModal open={!!selected} onClose={()=>setSelected(null)} finding={selected} technicians={technicians} onSave={onSaveAction}/></>
}
