import React,{useEffect,useState} from 'react'
import QRCode from 'qrcode'
import {Modal,Button,FormError} from './UI.jsx'
import {Printer} from '../icons.jsx'
import {machineLink} from '../lib/machineLink.js'
const currentBase=()=>{try{return localStorage.getItem('ij-qr-base-url')||location.href.split('#')[0]}catch{return location.href.split('#')[0]}}
export default function MachineQRModal({machines,onClose}){
 const [base,setBase]=useState(currentBase),[selected,setSelected]=useState(()=>machines.map(m=>m.id)),[labels,setLabels]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{let cancelled=false;setLoading(true);setLabels([]);setError('');(async()=>{try{const data=await Promise.all(machines.filter(m=>selected.includes(m.id)).map(async m=>{const url=machineLink(base,m.id);return {...m,url,image:await QRCode.toDataURL(url,{errorCorrectionLevel:'M',margin:4,width:512,color:{dark:'#000000',light:'#ffffff'}})}}));if(!cancelled){setLabels(data);try{localStorage.setItem('ij-qr-base-url',base)}catch{}}}catch(e){if(!cancelled)setError(e.message)}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[base,selected,machines])
 return <Modal open wide onClose={onClose} title="พิมพ์ QR Code ติดหน้าเครื่อง" subtitle="สแกนเพื่อดูข้อมูลและประวัติของเครื่องนั้น" footer={<><Button variant="ghost" onClick={onClose}>ปิด</Button><Button icon={Printer} disabled={loading||!!error||!labels.length} onClick={()=>window.print()}>พิมพ์ / บันทึก PDF ({labels.length})</Button></>}><div className="qr-settings"><label>URL เว็บที่เปิดใช้งานจริง<input type="url" value={base} onChange={e=>setBase(e.target.value)} placeholder="https://ชื่อเว็บของคุณ/ชื่อโครงการ/"/></label><p>ตรวจ URL ให้ตรงเว็บที่เพื่อนเปิดจากมือถือได้ รวมชื่อโครงการถ้ามี สแกนทดสอบก่อนติดป้าย</p><div className="qr-selection"><Button size="sm" variant="soft" onClick={()=>setSelected(machines.map(m=>m.id))}>เลือกทั้งหมด</Button><Button size="sm" variant="ghost" onClick={()=>setSelected([])}>ล้างที่เลือก</Button>{machines.map(m=><label key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/>{m.machine_no}</label>)}</div></div><FormError message={error}/>{loading&&<p>กำลังสร้าง QR Code…</p>}{!loading&&!error&&!labels.length&&<p>เลือกเครื่องที่ต้องการพิมพ์</p>}<div className="machine-qr-sheet">{labels.map(m=><article className="machine-qr-label" key={m.id}><b className="qr-machine-number">{m.machine_no}</b><span>{m.machine_name||'เครื่องจักร IJ'}</span><img src={m.image} alt={`QR Code ${m.machine_no}`} width="220" height="220"/><strong>สแกนดูข้อมูลเครื่อง</strong><span>ประวัติซ่อม · PM · TPM · ผลตรวจ</span><a href={m.url}>{new URL(m.url).host}</a></article>)}</div></Modal>
}
